/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HospitalMangMent;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newPatient = new javax.swing.JButton();
        upDown = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        FullHis = new javax.swing.JButton();
        Diagnosis = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS ICON/HMS ICON/add new patient.png"))); // NOI18N
        newPatient.setText("Add New Patient Record");
        newPatient.setPreferredSize(new java.awt.Dimension(240, 59));
        newPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPatientActionPerformed(evt);
            }
        });
        getContentPane().add(newPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 122, 225, -1));

        upDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS ICON/HMS ICON/two arrow.png"))); // NOI18N
        upDown.setPreferredSize(new java.awt.Dimension(240, 59));
        upDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upDownActionPerformed(evt);
            }
        });
        getContentPane().add(upDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 39, 75, -1));

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS ICON/HMS ICON/rsz_update_details.png"))); // NOI18N
        Update.setText("Update Patient Record");
        Update.setPreferredSize(new java.awt.Dimension(240, 59));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 335, 226, -1));

        FullHis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS ICON/HMS ICON/rsz_history1.png"))); // NOI18N
        FullHis.setText("Full History of the Patient");
        FullHis.setPreferredSize(new java.awt.Dimension(240, 59));
        FullHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullHisActionPerformed(evt);
            }
        });
        getContentPane().add(FullHis, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 264, 226, -1));

        Diagnosis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS ICON/HMS ICON/add diag.png"))); // NOI18N
        Diagnosis.setText("Add Diagnosis Information");
        Diagnosis.setPreferredSize(new java.awt.Dimension(240, 59));
        Diagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiagnosisActionPerformed(evt);
            }
        });
        getContentPane().add(Diagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 193, -1, -1));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS ICON/HMS ICON/exit.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.setPreferredSize(new java.awt.Dimension(240, 59));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 489, 200, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS ICON/HMS ICON/home.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
       int i = 0;
    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Did you really want to go to the login page", "Select", JOptionPane.YES_NO_OPTION);

        if (s == 0) {
            new login().setVisible(true);
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void upDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upDownActionPerformed
        if (i == 0) {
            upDown.setLocation(7, 30);
            newPatient.setLocation(90, 30);
            Diagnosis.setLocation(333, 30);
            FullHis.setLocation(576, 30);
            Update.setLocation(819, 30);
            Logout.setLocation(1062, 30);
            i = 1;
        } else {
            newPatient.setLocation(10, 107);
            Diagnosis.setLocation(10, 184);
            FullHis.setLocation(10, 261);
            Update.setLocation(10, 338);

            Logout.setLocation(10, 415);
            i = 0;
        }
    }//GEN-LAST:event_upDownActionPerformed

    private void newPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPatientActionPerformed
        new patientRecord().setVisible(true);
    }//GEN-LAST:event_newPatientActionPerformed

    private void DiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiagnosisActionPerformed
        new diagnosis().setVisible(true);
    }//GEN-LAST:event_DiagnosisActionPerformed

    private void FullHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullHisActionPerformed
        new fullhistory().setVisible(true);
    }//GEN-LAST:event_FullHisActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        new UpdatePatient().setVisible(true);
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Diagnosis;
    private javax.swing.JButton FullHis;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newPatient;
    private javax.swing.JButton upDown;
    // End of variables declaration//GEN-END:variables
}
